### ISSUE TITLE
Just an heads-up: Seems you forgot to upload it to the Godot asset library

### ISSUE THREAD

**Issue by duchainer** [MattUV/godot-MaxSizeContainer#1]
As mentioned in https://github.com/godotengine/godot-proposals/issues/1802#issuecomment-1024856822

Not an issue for me per-say, but I think many could find this addon useful :wink: 

Have a nice weekend :slightly_smiling_face:

**Comment by MattUV** [comment]
Hi! There it is!
https://godotengine.org/asset-library/asset/1210
However I don't know why it is under the "testing" category 🤔

**Comment by duchainer** [comment]
Ok I see it in the Web interface: 
![image](https://user-images.githubusercontent.com/11084784/166983062-b7f01c6b-a644-4077-a874-845bef3dfd20.png)
It may have been that the Testing ones are not shown in the Godot interface to the Asset Library? 
But now that it is in the `Support level`:`Community` it shows up as expected ^^ :
![image](https://user-images.githubusercontent.com/11084784/166983536-0a3941b7-7be8-4e34-8c66-72d8a854cd22.png)
Thanks for your good work and have a great weekend :smile:

**Comment by MattUV** [comment]
Hi @duchainer , thank you for reporting to me the problem. I asked the reason on another issue, and Hugo Locurio changed it from "testing" to "community".
Now there should be no more problem.

Merci !

**Comment by duchainer** [comment]
EN: You are welcome.
FR: De rien. ^^
